openNDS/openNDS

src/commandline.c, src/conf.h, src/debug.c, src/fw_iptables.c, src/fw_iptables.h, src/http_microhttpd.c, src/main.c, src/ndsctl.c, src/ndsctl_thread.c, src/ndsctl_thread.h, src/util.c, src/util.h
Initial renaming and bump to v5.0.0
=> Initial Rename and bump to v5.0.0beta

src/util.c
=> Fix missing newline (and test Travis config)

openwrt/opennds/Makefile, src/auth.c, src/conf.h, src/http_microhttpd.c, src/main.c
Bump to 5.02beta with numerous fixes
- BinAuth - Fix error passing client session times
- Fix PHP notice - undefined constant
- Fix OpenWrt CONFLICTS variable in Makefile
- set version to 5.0.2beta
=> Bump to 5.02beta with numerous fixes

docs/source/binauth.rst, docs/source/faq.rst, docs/source/install.rst
Corrections and additions to documentation.
=> Post readthedocs documentation proof reading fixes.

ChangeLog, debian/changelog, debian/doc/opennds.1, openwrt/opennds/Makefile, src/conf.h
=> Updates for release of version 5.1.0

forward_authentication_service/PreAuth/login.sh
Query string parsing could fail on adding new client data fields if a new
fieldname containd the name of another field.
eg gatewayaddress and address
=> Fix - PreAuth login.sh

openwrt/opennds/Makefile
=> Set OpenWrt Makefile to v6.0.1beta

src/util.c
=> Fix get_iface_ip in case of interface is vif or multihomed

Makefile, forward_authentication_service/libs/get_client_interface.sh, forward_authentication_service/libs/ipsetconfig.sh, openwrt/opennds/Makefile, openwrt/opennds/files/etc/config/opennds, openwrt/opennds/files/etc/init.d/opennds, resources/opennds.conf, src/conf.c, src/conf.h, src/fw_iptables.c, src/main.c, src/util.c
Walled Garden: Add Autonomous Operation
=> Walled Garden: Add Autonomous Operation

forward_authentication_service/PreAuth/login.sh
=> login.sh: make default shebang #!/bin/sh

docs/source/clientstatus.rst, docs/source/fas.rst, docs/source/index.rst, docs/source/overview.rst
=> Documentation updates

docs/source/fas.rst, forward_authentication_service/libs/client_params.sh, resources/opennds.conf, src/http_microhttpd.c, src/http_microhttpd_utils.c, src/ndsctl_thread.c, src/util.c
Various minor fixes/updates required after testing
=> 8.0.0beta Update

forward_authentication_service/PreAuth/login.sh, forward_authentication_service/fas-aes/fas-aes-https.php, forward_authentication_service/fas-aes/fas-aes.php, forward_authentication_service/libs/authmon.sh, linux_openwrt/opennds/files/etc/config/opennds, resources/opennds.conf
Some pre-release fixes after testing on OpenWrt, Rasbian and OpenSuse
=> 8.0.0beta Pre-release fixes

ChangeLog, docs/source/changelog.rst, linux_debian/changelog, linux_debian/doc/opennds.1
=> Fix: Date in changelog

src/main.c
=> Fix: main.c - option preauth ignored when set for custom script location

forward_authentication_service/libs/libopennds.sh, src/auth.c, src/http_microhttpd.c, src/ndsctl_thread.c
Adds improved MHD watchdog and fixes some legacy code.
=> Updates to V9.0.1beta

forward_authentication_service/libs/libopennds.sh
Signed-off-by: rob <rob@blue-wave.net>
=> MHD Watchdog - Use uclient-fetch in OpenWrt

src/ndsctl.c
ndsctl_unlock() was not receiving its file descriptor.
Lock was being released as nsdctl terminated, so it all worked anyway.
Signed-off-by: rob <rob@blue-wave.net>
=> Fix - editing errors preventing ndsctl_unlock() from working

linux_openwrt/opennds/files/etc/config/opennds, linux_openwrt/opennds/files/etc/init.d/opennds, src/conf.c, src/conf.h, src/http_microhttpd.c
This option allows an alternative client status page script to be used
Signed-off-by: rob <rob@blue-wave.net>
=> Add - option statuspath

ChangeLog, linux_debian/changelog
=> Fix - day of date in changelogs

docs/source/config.rst
=> Documentation update for configuration options

src/http_microhttpd.c
Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>
=> Fix - NULL pointer segfault in microhttpd on preauth

.travis.yml, src/http_microhttpd.c
Fix - Potential NULL pointer segfault in http_microhttpd on calling autenticated()
=> Fix - Potential NULL pointer segfault in http_microhttpd

linux_openwrt/opennds/files/etc/config/opennds
=> Add - updated comment in config file

docs/source/changelog.rst, linux_debian/doc/opennds.1
=> Documentation update

ChangeLog, docs/source/changelog.rst, linux_debian/changelog, linux_debian/doc/opennds.1, src/main.c
=> Fix - correctly display return buffer in syslog

forward_authentication_service/fas-aes/fas-aes-https.php, forward_authentication_service/fas-aes/fas-aes.php, forward_authentication_service/fas-hid/fas-hid.php, resources/splash.css
Add some CSS style to the default splash page to look fresher.
[Screenshot 1](https://user-images.githubusercontent.com/7848056/170845429-08a57be2-9efc-4677-a961-72c82531ca45.jpg)
[Screenshot 2](https://user-images.githubusercontent.com/7848056/170845507-4dedecb9-41d3-4bad-ba4c-15acca3c702a.jpg)
[Screenshot 3](https://user-images.githubusercontent.com/7848056/170845510-3363bce3-3da2-403b-be81-e67b6140d8cb.jpg)
[Screenshot 4](https://user-images.githubusercontent.com/7848056/170845513-a454c3fe-4bc3-4436-9186-d3a9f1215e46.jpg)
=> Add some cosmetic

ChangeLog, docs/source/changelog.rst
=> Update - Changelog for release

docs/source/libraries.rst
Fix arg number of write in documentation of libraries
=> Fix - Typo in libraries documentation

community/themespec/theme_legacy/README.md
=> Fix - typos in legacy ThemeSpec README.md

linux_openwrt/opennds/files/etc/config/opennds, src/auth.c, src/conf.c, src/conf.h, src/fw_iptables.c, src/fw_iptables.h
Add - Quota based Fair Usage Policy, sets throttled rate when quota exceeded
=> Add - Quota based Fair Usage Policy

forward_authentication_service/libs/libopennds.sh
Add - skip preemptivemac client if not dhcp database or is already authenticated
=> Add - skip preemptivemac client

forward_authentication_service/libs/dnsconfig.sh
=> Fix - ensure list dhcp-option-force is added to the correct dnsmasq zone

src/main.c, src/util.c, src/util.h
The existing version check is incorrect. This will properly check the version. Another option is to just check the major version and be done, but I'm pedantic and it's easy enough to check everything.
=> Fix - MHD version check rework
